### ISSUE TITLE
Back Button Closes Image Gallery

### ISSUE THREAD

**Issue by yawkity** [DialUpStuff/DialUpSite#1] opened 2016-04-29 16:05 UTC
On Mobile and Safari, photoswipe is closed when the back button is clicked, giving an empty black screen.

**Comment by bomanimc** [comment] 2016-11-23 04:44
@yawkity I can't reproduce this on mobile and Safari, but I don't remember if we intentionally fixed this. Closing for now.

**Closed by bomanimc** 2016-11-23 04:44 UTC
Labels: bug
